spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://119.23.57.79:3306/ds1?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 119.23.57.79
logging:
  level:
    com.yxj.esdemo.repository: debug

server:
  port: 8081